using System;
using System.Diagnostics;
using System.IO;

namespace PythonTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var res = RunPythonCommand("test.py", args[0], null);
            Console.WriteLine(res);
        }

        public static string RunPythonCommand(string command, string pythonExecPath, string args) 
        {
            var start = new ProcessStartInfo();
            start.FileName = pythonExecPath;
            start.Arguments = string.Format("\"{0}\" \"{1}\"", command, args);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return result;
                }
            }
        }
    }
}
